@startuml

!include <tupadr3/common>
!define ICONURL https://raw.githubusercontent.com/Roemer/plantuml-office/master/office2014
!includeurl ICONURL/Servers/database_server.puml
!includeurl ICONURL/Servers/domain_controller.puml
!includeurl ICONURL/Databases/database.puml
!includeurl ICONURL/Servers/application_server.puml
!includeurl ICONURL/Concepts/firewall_orange.puml
!includeurl ICONURL/Concepts/application_windows.puml
!includeurl ICONURL/Concepts/application_ios.puml
!includeurl ICONURL/Concepts/application_android.puml
!includeurl ICONURL/Concepts/globe_internet.puml
!includeurl ICONURL/Concepts/navigation.puml
!includeurl ICONURL/Clouds/cloud_disaster_red.puml
!includeurl ICONURL/Clouds/cloud.puml
!includeurl ICONURL/Clouds/public_im_cloud_service.puml
!includeurl ICONURL/Concepts/website.puml
!includeurl ICONURL/Concepts/web_services.puml
!includeurl ICONURL/Users/administrator.puml
!includeurl ICONURL/Devices/device_lcd_monitor.puml
!includeurl ICONURL/Devices/cell_phone_generic.puml
!includeurl ICONURL/Devices/device_laptop.puml
!includeurl ICONURL/Security/lock_protected.puml
!includeurl ICONURL/Users/user.puml
!includeurl ICONURL/Services/web_services.puml
!includeurl ICONURL/Services/3rd_party_service.puml

!includeurl https://raw.githubusercontent.com/RicardoNiepel/C4-PlantUML/release/1-0/C4_Container.puml
!define AzurePuml https://raw.githubusercontent.com/RicardoNiepel/Azure-PlantUML/release/1-0/dist
!includeurl AzurePuml/AzureCommon.puml
!includeurl AzurePuml/InternetOfThings/all.puml
!includeurl AzurePuml/Databases/AzureSqlDatabase.puml
!includeurl AzurePuml/Databases/AzureCosmosDb.puml
!includeurl AzurePuml/Databases/AzureRedisCache.puml
!includeurl AzurePuml/Compute/AzureFunction.puml
'!includeurl AzurePuml/Compute/AzureVirtualMachine.puml
!includeurl AzurePuml/Compute/AzureAppService.puml
'!includeurl AzurePuml/Analytics/AzureStreamAnalytics.puml
'!includeurl AzurePuml/DevOps/AzureLabServices.puml
'!includeurl AzurePuml/DevOps/AzureDevTestLabs.puml
'!includeurl AzurePuml/DevOps/AzurePipelines.puml
!includeurl AzurePuml/General/Azure.puml
!includeurl AzurePuml/Integration/AzureLogicApps.puml
!includeurl AzurePuml/Integration/AzureEventGrid.puml
!includeurl AzurePuml/Integration/AzureServiceBus.puml
!includeurl AzurePuml/Identity/AzureActiveDirectory.puml
!includeurl AzurePuml/Storage/AzureBlobStorage.puml
!includeurl AzurePuml/Storage/AzureQueueStorage.puml
!includeurl AzurePuml/Storage/AzureFileStorage.puml
'!includeurl AzurePuml/Networking/AzureLoadBalancer.puml
!includeurl AzurePuml/Networking/AzureDNS.puml
!includeurl AzurePuml/Networking/AzureApplicationGateway.puml
!includeurl AzurePuml/Web/AzureWebApp.puml
!includeurl AzurePuml/Web/AzureCDN.puml
!includeurl AzurePuml/Web/AzureSearch.puml
!includeurl AzurePuml/Web/AzureAPIManagement.puml
!includeurl AzurePuml/Management/AzureResourceManager.puml

title Basic Enterprise Integration on Azure
left to right direction
together {  
    AzureActiveDirectory(aad, "Azure\nActive Directory", "active directory")
    OFF_NAVIGATION(client, "Client       Apps") #FFFFFF
    aad -[hidden]> client
}

Boundary(rg, "Resource Group"){
    Boundary(wrk_orch, "Workflow and Orchestration") #CFDFFF{                
        AzureLogicApps(logic01, "Logic Apps", "logic app")
        AzureLogicApps(logic02, "Logic Apps", "logic app")
        logic01 -[hidden]- logic02
    }
    
    Boundary(api_mgmt, "API Management") #CFDFFF{   
        AzureAPIManagement(api01, "API gateway", "api gateway")     
        
    }
    
    Boundary(queues, "Queues and events") #CFDFFF{   
        AzureEventGrid(evnt_grid, "Event Grid", "event grid")
        AzureServiceBus(svc_bus, "Service Bus", "service bus")
        svc_bus -[hidden]- evnt_grid
    }

    'rectangle "<color:#0072C6><$AzureResourceManager></color>" as rglogo #FFFFFF
    api01 -[hidden]- logic01
    'api02-[hidden]-rglogo
    'rglogo -[hidden]> api01
    svc_bus -[hidden]> logic01

    
    'logic ..> api02: Publish interfaces
}

Boundary(backend, "Backend systems") {

    OFF_PUBLIC_IM_CLOUD_SERVICE(msg_svc, "Message  -  based\nservices") #FFFFFF
    Azure(az_svc, "Azure Services\n", "")
    OFF_PUBLIC_IM_CLOUD_SERVICE(saas, "\nSaas       Services") #FFFFFF
    OFF_WEB_SERVICES(rest, "REST     /     SOAP") #FFFFFF

    msg_svc -[hidden]> az_svc
    az_svc -[hidden]> saas
    
}

logic02 -[hidden]- saas
api01 -[hidden]- logic01
client --> api01: HTTP
api01 -> logic01: HTTP

evnt_grid .> logic02
logic01 .> svc_bus
svc_bus .> evnt_grid

logic02 -> saas: HTTP
logic02 -> az_svc
'evnt_grid .right.> az_svc: Events
'az_svc .up.> evnt_grid
svc_bus <.. msg_svc: Messages

api01 -----> rest: HTTP
'aad -[hidden]> client
aad <. client


@enduml